<WidgetHostAddress>:
    orientation: "vertical"
    Label:
        text: ""
        size_hint: 1, .3
    Label:
        text: "Host Address"
        size_hint: 1, .4
        font_size: "55dp"
        font_name: "fonts/YuGothB.ttc"
    Label:
        text: "Choose the default host or"
        size_hint: 1, .15
        font_size: "25dp"
        font_name: "fonts/YuGothR.ttc"
    Label:
        text: "create your own one:"
        size_hint: 1, .15
        font_size: "25dp"
        font_name: "fonts/YuGothR.ttc"
    Label:
        text: ""
        size_hint: 1, .3
    BoxLayout:
        orientation: "vertical"

        Button:
            text: "Connect"
            font_size: "25dp"
            size_hint: .6, .4
            pos_hint: {"center_x": .5}
            on_release: root.button_connect()
            font_name: "fonts/YuGothM.ttc"
    Label:
        text: ""
        size_hint: 1, .3
    WidgetInfoLine:

<WidgetWelcome>:
    orientation: "vertical"
    Label:
        text: ""
        size_hint: 1, .3
    Label:
        text: "Shop Link"
        size_hint: 1, .4
        font_size: "55dp"
        font_name: "fonts/YuGothB.ttc"
    Label:
        text: "by " + root.app.author
        size_hint: 1, .2
        font_size: "25dp"
        font_name: "fonts/YuGothM.ttc"
    Label:
        text: "Welcome!"
        font_size: "40dp"
        pos_hint: {"center_x": .5}
        font_name: "fonts/YuGothR.ttc"
    Button:
        text: "Get started"
        font_size: "25dp"
        size_hint: .6, .4
        pos_hint: {"center_x": .5}
        on_release: root.button_get_started()
        font_name: "fonts/YuGothM.ttc"
    Label:
        text: ""
        size_hint: 1, .3
    WidgetInfoLine:

<WidgetInfoLine>:
    size_hint: 1, None
    height: "35dp"
    AnchorLayout:
        anchor_x: "left"
        Label:
            text: root.version
            font_size: "16dp"
            size_hint: None, 1
            width: "80dp"
            font_name: "fonts/YuGothL.ttc"
    AnchorLayout:
        anchor_x: "center"
        Label:
            text: "Shop Ready"
            font_size: "16dp"
            font_name: "fonts/YuGothL.ttc"
    AnchorLayout:
        anchor_x: "right"
        Label:
            text: root.author
            font_size: "16dp"
            size_hint: None, 1
            width: "80dp"
            font_name: "fonts/YuGothL.ttc"
